PyCon Open Spaces example content
adafruit/PyCon2019 pull request #8
Opened 2019-04-24 16:54 UTC by kattni

Please test as many of these as possible. @makermelissa I was unable to add you as a reviewer, so I am adding you here.

While testing, please verify the following:
* Each example works.
* Each example has a docstring with a quick explanation
* Examples requiring external hardware have connection instructions in the docstring
* Examples that require an external library have a huge note in the docstring stating the need and indicating the library or libraries needed.
* Examples are clear and simple as possible (which in some cases means longer for readability)

Hardware needed to test all the examples:
* 2 Circuit Playground Expresses (1 will work for everything but the IR examples)
* A micro servo (alligator-to-jumper-wire clips are easiest to connect it with)
* A 10k potentiometer (and alligator clips)
* A 30-pixel NeoPixel strip with alligator clips

Please leave do not merge until everything has been tested.

Thank so much!

2019-04-24 17:22 UTC, makermelissa commented
I only have 1 CPX. Should I order another or just not test IR? I should have enough of the other stuff to kludge together some test accessories.

2019-04-24 17:25 UTC, kattni commented
@makermelissa Don't worry about testing IR. Most of the examples do not require any hardware at all, so even if you don't have the listed hardware, you can still do quite a bit.

2019-04-24 17:41 UTC, makermelissa commented
Ok, sounds good.

2019-04-25 05:31 UTC, makermelissa commented
Parts ordered, but I'm going to start testing the ones that don't require parts until then. This may take a bit. :)

2019-04-25 05:46 UTC, makermelissa commented
Which version of CircuitPython should we be testing these one. AFAIK, they shipped with CP 3.1.2, but CP 4 should be out by then. For now I'm going to test with CP 4.

2019-04-25 13:12 UTC, dhalbert commented
They shipped with 3.1.2, so test with that. 4.0.0 will probably be final by PyCon, but we couldn't be sure, and there will always be bugs. 3.1.2 has a longer history of general use. If you want to test with both, that would be great, but not necessary.

2019-04-25 14:05 UTC, makermelissa commented
Thanks @danh.

2019-04-25 15:36 UTC, kattni commented
@dhalbert @makermelissa That is incorrect, they shipped with 4.0.0-beta.7. Please test with that version. Thanks!

2019-04-25 17:56 UTC, makermelissa commented
Ok, thanks @kattni

2019-04-25 19:45 UTC, siddacious commented
@makermelissa Since I have most of the parts required, I'll start on the ones that do require them and then we'll pass somewhere in the middle? I should be able to gets started later today.

2019-04-25 20:03 UTC, makermelissa commented
Sounds good. It also doesn’t hurt if some stuff is tested by both of us.

2019-04-25 20:15 UTC, kattni commented
Hi all! @brentru may be joining in the testing. So, please continue to communicate about where you're at with testing so everyone is on the same page. Thanks!!

2019-04-25 20:15 UTC, siddacious commented
Right, that's what I meant by "pass in the middle" assuming we were both going to test most things.

2019-04-25 20:17 UTC, makermelissa commented
Ah right. Sounds good.

2019-04-26 02:44 UTC, makermelissa commented
Just one minor thing I found. In `cpx_buttons_1_neopixel.py` it doesn't quite do what the description says. For instance, if you hold button B and then press button A at the same time and then let go of button B, both lights remain on while you continue holding button A.

2019-04-26 02:45 UTC, makermelissa commented
Same thing with `cpx_buttons_neopixels.py`

2019-04-26 06:19 UTC, makermelissa commented
I've tested everything in Circuit_Playground_Express_Examples and everything in Circuit_Playground_Express_cpx_Library_Examples (except IR examples for now). I'll finish testing the rest of the examples tomorrow when I get the additional parts.

2019-04-26 23:11 UTC, makermelissa requested changes
I finished testing all examples. I had some earlier comments and there was only one example that wasn't working which I requested changes on. Everything else is looking good.

2019-04-26 23:11 UTC, makermelissa commented on Accessory_Examples/buttons_servo.py
> +    if cpx.button_A:
I needed to change this to lowercase button_a to get it to function.

2019-04-26 23:11 UTC, makermelissa commented on Accessory_Examples/buttons_servo.py
> +    elif cpx.button_B:
Same with the button_b

2019-04-27 05:56 UTC, ntoll commented
You folks rock.

2019-04-27 22:02 UTC, kattni commented
@ntoll Thanks! 😊 And thank you for the pulsing Python logo example - I've included it in this PR to be part of our Open Spaces content!

2019-04-27 22:07 UTC, kattni commented
@makermelissa @siddacious I would like to merge this PR tonight sometime, as I need to continue adding to this repo. If anyone has any further suggestions, please get them in. We can always do another PR if any issues are found after merging.

2019-04-27 23:05 UTC, makermelissa approved these changes
Looks good. Thanks.

2019-04-28 00:24 UTC, siddacious requested changes
Everything works fine but a few doc strings were a bit confusing, possibly due to me not using what I assume is going to be hardware that is provided. A handful of opinions about possible other tweaks but take them as you will.

2019-04-28 00:24 UTC, siddacious commented on Accessory_Examples/buttons_servo.py
> +Connect the red clip (red wire) on the servo to a 3.3v pad.
These should read "Connect the x clip to the y wire on the servo to z pad"

2019-04-28 00:24 UTC, siddacious commented on Accessory_Examples/buttons_servo.py
> +Connect the red clip (red wire) on the servo to a 3.3v pad.
Also the yellow wire looks kinda orange

2019-04-28 00:24 UTC, siddacious commented on Accessory_Examples/potentiometer_neopixel_strip.py
> +"""Connect the blue clip on the potentiometer to A0, and the white clip on the NeoPixel strip to A7.
I'm now kinda thinking that these should also list the required hardware, then the connections. Should be obvious but it isn't always.

2019-04-28 00:24 UTC, siddacious commented on Accessory_Examples/potentiometer_neopixel_strip.py
> +"""Connect the blue clip on the potentiometer to A0, and the white clip on the NeoPixel strip to A7.
I think these are meant to be followed with provided hardware that matches the colors given but it's somewhat unclear if that's not the case.

2019-04-28 00:24 UTC, siddacious commented on Circuit_Playground_Express_Examples/light_sensor.py
> +    print(light_sensor.value)
It is a little confusing that this prints different values than the similar example using the cpx lib

2019-04-28 00:24 UTC, siddacious commented on Circuit_Playground_Express_cpx_Library_Examples/cpx_light_plotter.py
> +    time.sleep(1)
Personally I think the graph/plot is more interactive with a shorter sleep

2019-04-28 00:24 UTC, siddacious commented on Circuit_Playground_Express_cpx_Library_Examples/cpx_shake.py
> +        print("Shake detected!")
Either I have a literal limp wrist or the threshold on shake is too high. Or both. I had to shake what seemed excessively hard to get a shake to register

2019-04-28 00:24 UTC, siddacious commented on Circuit_Playground_Express_cpx_Library_Examples/cpx_slide_switch_red_led.py
> +# Can also be written as:
This isn't needed if there is going to be a separate example that does the same thing

2019-04-28 00:24 UTC, siddacious commented on Circuit_Playground_Express_cpx_Library_Examples/cpx_temperature_neopixels.py
> +# Set these based on your ambient temperature for best results!
This should probably mention that it's in celcius

2019-04-28 00:24 UTC, siddacious commented on Circuit_Playground_Express_cpx_Library_Examples/cpx_temperture_plotter.py
> +    time.sleep(1)
as above, I think a smaller sleep will make the plot more interactive and interesting

2019-04-28 00:24 UTC, siddacious commented on Circuit_Playground_Express_cpx_Library_Examples/cpx_touch_tone_machine.py
> +pads on A1-A7 to hear a funky scale of notes!"""
The "I had to memorize all the major and minor scales" part of my brain hates this but it works great!

2019-04-28 02:06 UTC, siddacious approved these changes

2019-04-28 02:06 UTC, merged

2019-04-28 02:07 UTC, siddacious commented
great, thanks!